[package]
name = "many-fuzzy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
cbor-diag = "0.1.8"
clap = { version = "3.0.0-rc.9", features = [ "derive" ] }
hdrhistogram = "7.5.0"
many = { git = "https://github.com/l-1-labs/many-rs.git" }
many-client = { git = "https://github.com/l-1-labs/many-rs.git" }
minicose = { git = "https://git@github.com/l-1-labs/rust-minicose.git", features = [ "allow-unsigned" ] }
peg = "0.8.0"
proptest = "1.0.0"
rand = { version = "0.8.5", features = [ "std_rng" ] }
rand_distr = "0.4.3"
regex = "1.5.5"
reqwest = "0.11.10"
tracing = "0.1.29"
tracing-subscriber = "0.2.24"
tracing-timing = "0.6.0"
tokio = { version = "1.12.0", features = [ "full" ] }
url = "2.2.2"
